VolD: de.zib.vold.userInterface.ABI Class Reference
de.zib.vold.userInterface.ABI Class Reference
Application Binary Interface to VolD.
Static Public Member Functions
static void main (String[] args)
Private Member Functions
ABI ()
Private Attributes
final Frontend frontend
ApplicationContext context
Static Private Attributes
static final Logger log = LoggerFactory.getLogger(ABI.class)
Detailed Description
Application Binary Interface to VolD.
The ABI reads commands from stdin and prints the results to stdout.
Definition at line 31 of file ABI.java.
Constructor & Destructor Documentation
de.zib.vold.userInterface.ABI.ABI () [private]
Definition at line 40 of file ABI.java.
References de.zib.vold.userInterface.ABI.context, and de.zib.vold.userInterface.ABI.frontend.
Referenced by de.zib.vold.userInterface.ABI.main().
Member Function Documentation
static void de.zib.vold.userInterface.ABI.main (String[] args) [static]
Definition at line 48 of file ABI.java.
References de.zib.vold.userInterface.ABI.ABI(), de.zib.vold.userInterface.ABI.frontend, de.zib.vold.common.Key.get_keyname(), de.zib.vold.common.Key.get_scope(), de.zib.vold.common.Key.get_type(), de.zib.vold.frontend.Frontend.insert(), and de.zib.vold.frontend.Frontend.lookup().
Member Data Documentation
ApplicationContext de.zib.vold.userInterface.ABI.context [private]
Definition at line 38 of file ABI.java.
Referenced by de.zib.vold.userInterface.ABI.ABI().
final Frontend de.zib.vold.userInterface.ABI.frontend [private]
Definition at line 35 of file ABI.java.
Referenced by de.zib.vold.userInterface.ABI.ABI(), and de.zib.vold.userInterface.ABI.main().
final Logger de.zib.vold.userInterface.ABI.log = LoggerFactory.getLogger(ABI.class) [static, private]
Definition at line 33 of file ABI.java.
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/userInterface/ABI.java