VolD: de.zib.vold.replication.LocalReplicator Class Reference
de.zib.vold.replication.LocalReplicator Class Reference
Simple Replicator delegating all requests to a VolatileDirectory.
Public Member Functions
LocalReplicator (VolatileDirectory replica)
Construct a LocalReplicator with its backend to use.
LocalReplicator ()
Construct an unitialized LocalReplicator.
void setReplica (VolatileDirectory replica)
Set the VolatileDirectory backend.
void checkState ()
Internal method which acts as part of the guard of all public methods.
void insert (List< String > key, Set< String > value)
Delegate an insert request.
void refresh (List< String > key)
Delegate a refresh request.
void delete (List< String > key)
Delegate a delete request.
Protected Attributes
final Logger log = LoggerFactory.getLogger(this.getClass())
Private Attributes
VolatileDirectory replica
Detailed Description
Simple Replicator delegating all requests to a VolatileDirectory.
This class helps in building replication trees.
See also:
Replicator
Definition at line 19 of file LocalReplicator.java.
Constructor & Destructor Documentation
de.zib.vold.replication.LocalReplicator.LocalReplicator (VolatileDirectory replica)
Construct a LocalReplicator with its backend to use.
Parameters:
replica The VolatileDirectory to delegate the write request to.
Definition at line 29 of file LocalReplicator.java.
References de.zib.vold.replication.LocalReplicator.replica.
de.zib.vold.replication.LocalReplicator.LocalReplicator ()
Construct an unitialized LocalReplicator.
Definition at line 37 of file LocalReplicator.java.
References de.zib.vold.replication.LocalReplicator.replica.
Member Function Documentation
void de.zib.vold.replication.LocalReplicator.checkState ()
Internal method which acts as part of the guard of all public methods.
Definition at line 55 of file LocalReplicator.java.
References de.zib.vold.replication.LocalReplicator.replica.
Referenced by de.zib.vold.replication.LocalReplicator.delete(), de.zib.vold.replication.LocalReplicator.insert(), and de.zib.vold.replication.LocalReplicator.refresh().
void de.zib.vold.replication.LocalReplicator.delete (List< String > key)
Delegate a delete request.
Parameters:
key The key to replicate the request for.
Implements de.zib.vold.replication.Replicator.
Definition at line 106 of file LocalReplicator.java.
References de.zib.vold.replication.LocalReplicator.checkState(), de.zib.vold.volatilelogic.SlicedDirectory.delete(), de.zib.vold.replication.LocalReplicator.log, and de.zib.vold.replication.LocalReplicator.replica.
void de.zib.vold.replication.LocalReplicator.insert (List< String > key, Set< String > value)
Delegate an insert request.
Parameters:
key The key to replicate the request for.
value The values associated to the key.
Implements de.zib.vold.replication.Replicator.
Definition at line 70 of file LocalReplicator.java.
References de.zib.vold.replication.LocalReplicator.checkState(), de.zib.vold.volatilelogic.SimpleDirectory.insert(), de.zib.vold.replication.LocalReplicator.log, and de.zib.vold.replication.LocalReplicator.replica.
void de.zib.vold.replication.LocalReplicator.refresh (List< String > key)
Delegate a refresh request.
Parameters:
key The key to replicate request for.
Implements de.zib.vold.replication.Replicator.
Definition at line 88 of file LocalReplicator.java.
References de.zib.vold.replication.LocalReplicator.checkState(), de.zib.vold.replication.LocalReplicator.log, de.zib.vold.volatilelogic.SimpleDirectory.refresh(), and de.zib.vold.replication.LocalReplicator.replica.
void de.zib.vold.replication.LocalReplicator.setReplica (VolatileDirectory replica)
Set the VolatileDirectory backend.
Parameters:
replica The VolatileDirectory to delegate the write request to.
Definition at line 47 of file LocalReplicator.java.
References de.zib.vold.replication.LocalReplicator.replica.
Member Data Documentation
final Logger de.zib.vold.replication.LocalReplicator.log = LoggerFactory.getLogger(this.getClass()) [protected]
Definition at line 21 of file LocalReplicator.java.
Referenced by de.zib.vold.replication.LocalReplicator.delete(), de.zib.vold.replication.LocalReplicator.insert(), and de.zib.vold.replication.LocalReplicator.refresh().
VolatileDirectory de.zib.vold.replication.LocalReplicator.replica [private]
Definition at line 22 of file LocalReplicator.java.
Referenced by de.zib.vold.replication.LocalReplicator.checkState(), de.zib.vold.replication.LocalReplicator.delete(), de.zib.vold.replication.LocalReplicator.insert(), de.zib.vold.replication.LocalReplicator.LocalReplicator(), de.zib.vold.replication.LocalReplicator.refresh(), and de.zib.vold.replication.LocalReplicator.setReplica().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/replication/LocalReplicator.java