VolD: de.zib.vold.frontend.Reaper.ReaperWorker Class Reference
de.zib.vold.frontend.Reaper.ReaperWorker Class Reference
The Worker class for the reaper.
Public Member Functions
ReaperWorker (SlicedDirectory directory, long timeslice, long TTL)
void run ()
Private Member Functions
void reap_timeslice (long timeslice)
Private Attributes
SlicedDirectory directory
long timeslice
long ttl
Detailed Description
The Worker class for the reaper.
This class reaps too old keys for a certain timeslice.
Definition at line 209 of file Reaper.java.
Constructor & Destructor Documentation
de.zib.vold.frontend.Reaper.ReaperWorker.ReaperWorker (SlicedDirectory directory, long timeslice, long TTL)
Definition at line 215 of file Reaper.java.
References de.zib.vold.frontend.Reaper.ReaperWorker.directory, de.zib.vold.frontend.Reaper.ReaperWorker.timeslice, and de.zib.vold.frontend.Reaper.ReaperWorker.ttl.
Member Function Documentation
void de.zib.vold.frontend.Reaper.ReaperWorker.reap_timeslice (long timeslice) [private]
Definition at line 246 of file Reaper.java.
References de.zib.vold.volatilelogic.SlicedDirectory.delete(), de.zib.vold.frontend.Reaper.ReaperWorker.directory, de.zib.vold.frontend.Reaper.log, de.zib.vold.volatilelogic.SlicedDirectory.sliceLookup(), and de.zib.vold.frontend.Reaper.ReaperWorker.ttl.
Referenced by de.zib.vold.frontend.Reaper.ReaperWorker.run().
void de.zib.vold.frontend.Reaper.ReaperWorker.run ()
Definition at line 231 of file Reaper.java.
References de.zib.vold.frontend.Reaper.log, de.zib.vold.frontend.Reaper.ReaperWorker.reap_timeslice(), and de.zib.vold.frontend.Reaper.ReaperWorker.timeslice.
Member Data Documentation
SlicedDirectory de.zib.vold.frontend.Reaper.ReaperWorker.directory [private]
Definition at line 211 of file Reaper.java.
Referenced by de.zib.vold.frontend.Reaper.ReaperWorker.reap_timeslice(), and de.zib.vold.frontend.Reaper.ReaperWorker.ReaperWorker().
long de.zib.vold.frontend.Reaper.ReaperWorker.timeslice [private]
Definition at line 212 of file Reaper.java.
Referenced by de.zib.vold.frontend.Reaper.ReaperWorker.ReaperWorker(), and de.zib.vold.frontend.Reaper.ReaperWorker.run().
long de.zib.vold.frontend.Reaper.ReaperWorker.ttl [private]
Definition at line 213 of file Reaper.java.
Referenced by de.zib.vold.frontend.Reaper.ReaperWorker.reap_timeslice(), and de.zib.vold.frontend.Reaper.ReaperWorker.ReaperWorker().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/frontend/Reaper.java