VolD: de.zib.vold.frontend.Reaper Class Reference
de.zib.vold.frontend.Reaper Class Reference
GarbageCollector for VolD.
Classes
class ReaperWorker
The Worker class for the reaper.
Public Member Functions
Reaper (SlicedDirectory directory, long TTL)
Construct an initialized Reaper.
Reaper ()
Construct an uninitialized Reaper.
void setTTL (long ttl)
Set the time a key may live.
void setSlicedDirectory (SlicedDirectory slicedDirectory)
Set the directory the Reaper should work on.
void stop_service ()
Stop the thread running in the background.
void start ()
Start the Reaper in background.
void run ()
Start the reaper in foreground.
void reap ()
Work until the run flag is set to false.
Protected Member Functions
void checkState ()
Internal method which acts as part of the guard of all public methods.
Protected Attributes
final Logger log = LoggerFactory.getLogger(this.getClass())
Private Attributes
boolean run
long ttl
SlicedDirectory directory
Detailed Description
GarbageCollector for VolD.
The Reaper deletes keys which are older than a certain time to live (TTL). The TTL is a soft limit. Hence, a key may exist longer than the TTL but never twice as much.
Definition at line 24 of file Reaper.java.
Constructor & Destructor Documentation
de.zib.vold.frontend.Reaper.Reaper (SlicedDirectory directory, long TTL)
Construct an initialized Reaper.
Parameters:
directory The directory to collect the garbage in.
TTL The age a key is allowed to reach.
Definition at line 40 of file Reaper.java.
References de.zib.vold.frontend.Reaper.directory, de.zib.vold.frontend.Reaper.run(), and de.zib.vold.frontend.Reaper.ttl.
de.zib.vold.frontend.Reaper.Reaper ()
Construct an uninitialized Reaper.
Definition at line 59 of file Reaper.java.
References de.zib.vold.frontend.Reaper.directory, de.zib.vold.frontend.Reaper.run(), and de.zib.vold.frontend.Reaper.ttl.
Member Function Documentation
void de.zib.vold.frontend.Reaper.checkState () [protected]
Internal method which acts as part of the guard of all public methods.
Definition at line 69 of file Reaper.java.
References de.zib.vold.frontend.Reaper.directory, and de.zib.vold.frontend.Reaper.ttl.
Referenced by de.zib.vold.frontend.Reaper.reap(), de.zib.vold.frontend.Reaper.run(), and de.zib.vold.frontend.Reaper.stop_service().
void de.zib.vold.frontend.Reaper.reap ()
Work until the run flag is set to false.
Definition at line 156 of file Reaper.java.
References de.zib.vold.frontend.Reaper.checkState(), de.zib.vold.frontend.Reaper.directory, de.zib.vold.volatilelogic.SlicedDirectory.getActualSlice(), de.zib.vold.volatilelogic.SlicedDirectory.getTimeSliceSize(), de.zib.vold.frontend.Reaper.log, de.zib.vold.frontend.Reaper.run(), and de.zib.vold.frontend.Reaper.ttl.
Referenced by de.zib.vold.frontend.Reaper.run().
void de.zib.vold.frontend.Reaper.run ()
Start the reaper in foreground.
Definition at line 142 of file Reaper.java.
References de.zib.vold.frontend.Reaper.checkState(), and de.zib.vold.frontend.Reaper.reap().
Referenced by de.zib.vold.frontend.Reaper.reap(), de.zib.vold.frontend.Reaper.Reaper(), and de.zib.vold.frontend.Reaper.stop_service().
void de.zib.vold.frontend.Reaper.setSlicedDirectory (SlicedDirectory slicedDirectory)
Set the directory the Reaper should work on.
Definition at line 95 of file Reaper.java.
References de.zib.vold.frontend.Reaper.directory, and de.zib.vold.frontend.Reaper.log.
void de.zib.vold.frontend.Reaper.setTTL (long ttl)
Set the time a key may live.
Parameters:
ttl The age a key may reach.
Definition at line 82 of file Reaper.java.
References de.zib.vold.frontend.Reaper.ttl.
void de.zib.vold.frontend.Reaper.start ()
Start the Reaper in background.
Definition at line 134 of file Reaper.java.
void de.zib.vold.frontend.Reaper.stop_service ()
Stop the thread running in the background.
Definition at line 109 of file Reaper.java.
References de.zib.vold.frontend.Reaper.checkState(), de.zib.vold.frontend.Reaper.log, and de.zib.vold.frontend.Reaper.run().
Member Data Documentation
SlicedDirectory de.zib.vold.frontend.Reaper.directory [private]
Definition at line 30 of file Reaper.java.
Referenced by de.zib.vold.frontend.Reaper.checkState(), de.zib.vold.frontend.Reaper.reap(), de.zib.vold.frontend.Reaper.Reaper(), and de.zib.vold.frontend.Reaper.setSlicedDirectory().
final Logger de.zib.vold.frontend.Reaper.log = LoggerFactory.getLogger(this.getClass()) [protected]
Definition at line 32 of file Reaper.java.
Referenced by de.zib.vold.frontend.Reaper.reap(), de.zib.vold.frontend.Reaper.ReaperWorker.reap_timeslice(), de.zib.vold.frontend.Reaper.ReaperWorker.run(), de.zib.vold.frontend.Reaper.setSlicedDirectory(), and de.zib.vold.frontend.Reaper.stop_service().
boolean de.zib.vold.frontend.Reaper.run [private]
Definition at line 26 of file Reaper.java.
long de.zib.vold.frontend.Reaper.ttl [private]
Definition at line 29 of file Reaper.java.
Referenced by de.zib.vold.frontend.Reaper.checkState(), de.zib.vold.frontend.Reaper.reap(), de.zib.vold.frontend.Reaper.Reaper(), and de.zib.vold.frontend.Reaper.setTTL().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/frontend/Reaper.java