VolD: de.zib.vold.backend.FileSystemDirectory Class Reference
de.zib.vold.backend.FileSystemDirectory Class Reference
Implementation of PartitionedDirectoryBackend based on a file system structure.
Classes
class PrefixFilter
The prefix filter helps filtering files with a certain prefix.
Public Member Functions
FileSystemDirectory (String path, String enc)
Construct a FileSystemDirectory with all necessary informations.
FileSystemDirectory ()
Construct a FileSystemDirectory without initialization.
void setRootPath (String rootPath)
Set the root directory where to store the database.
void setEnc (String enc)
Set the encoding.
void checkState ()
Internal method which acts as part of the guard of all public methods.
void open ()
Open the database.
void close ()
Close the database.
boolean isopen ()
Query the state of the database.
void insert (int partition, List< String > key, List< String > value)
Insert a key with its set of values into a partition.
void delete (int partition, List< String > key)
Delete the key and its values from a partition.
List< String > lookup (int partition, List< String > key)
Query the values for a key in a partition (root subdirectory).
Map< List< String >, List
< String > > prefixlookup (int partition, List< String > key)
Query the entries with all keys beginning with a prefix.
Protected Attributes
final Logger log = LoggerFactory.getLogger(this.getClass())
Private Member Functions
void recursive_add (List< String > key, String dir, Map< List< String >, List< String > > map)
Recursively add all keys with its values to the map.
void file_add (List< String > key, String value, Map< List< String >, List< String > > map)
Add a key with its values to the map.
String _buildpath (List< String > dir)
Convert the key to a path.
List< String > _get_partition_dir (int partition, List< String > dir)
Prepend the partition to a key.
String _buildfile (String dir)
Convert the value to a filename.
String buildfile (String dir)
Convert the filename to a value.
String _builddir (String dir)
Convert to key (only one part of it) to a directory name.
String builddir (String dir)
Convert the directory name to a part of key.
Private Attributes
File root
String rootPath
String enc = "utf-8"
Detailed Description
Implementation of PartitionedDirectoryBackend based on a file system structure.
Here, a key will be a subdirectory and the values will be its files. To avoid name clashing of keys and files, a plus ('+') will be prepended to keys (i.e. to directory names) and a minus ('-') will be prepended to files (i.e. to values). Different partitions will be represented by different directories in the root.
See also:
PartitionedDirectoryBackend
Author:
Jörg Bachmann (bachmann@zib.de)
Definition at line 38 of file FileSystemDirectory.java.
Constructor & Destructor Documentation
de.zib.vold.backend.FileSystemDirectory.FileSystemDirectory (String path, String enc)
Construct a FileSystemDirectory with all necessary informations.
Note:
This constructor will not open the interface. This still has to be done using the open method.
Parameters:
root The root directory where to store the database.
encoding The encoding which will be used.
Definition at line 55 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.enc, de.zib.vold.backend.FileSystemDirectory.root, and de.zib.vold.backend.FileSystemDirectory.rootPath.
de.zib.vold.backend.FileSystemDirectory.FileSystemDirectory ()
Construct a FileSystemDirectory without initialization.
Definition at line 65 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.root, and de.zib.vold.backend.FileSystemDirectory.rootPath.
Member Function Documentation
String de.zib.vold.backend.FileSystemDirectory._builddir (String dir) [private]
Convert to key (only one part of it) to a directory name.
Definition at line 598 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.enc.
Referenced by de.zib.vold.backend.FileSystemDirectory._get_partition_dir(), and de.zib.vold.backend.FileSystemDirectory.prefixlookup().
String de.zib.vold.backend.FileSystemDirectory._buildfile (String dir) [private]
Convert the value to a filename.
Definition at line 567 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.enc.
Referenced by de.zib.vold.backend.FileSystemDirectory.insert().
String de.zib.vold.backend.FileSystemDirectory._buildpath (List< String > dir) [private]
Convert the key to a path.
Definition at line 528 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.rootPath.
Referenced by de.zib.vold.backend.FileSystemDirectory.delete(), de.zib.vold.backend.FileSystemDirectory.insert(), de.zib.vold.backend.FileSystemDirectory.lookup(), and de.zib.vold.backend.FileSystemDirectory.prefixlookup().
List< String > de.zib.vold.backend.FileSystemDirectory._get_partition_dir (int partition, List< String > dir) [private]
Prepend the partition to a key.
Definition at line 543 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory._builddir().
Referenced by de.zib.vold.backend.FileSystemDirectory.delete(), de.zib.vold.backend.FileSystemDirectory.insert(), de.zib.vold.backend.FileSystemDirectory.lookup(), and de.zib.vold.backend.FileSystemDirectory.prefixlookup().
String de.zib.vold.backend.FileSystemDirectory.builddir (String dir) [private]
Convert the directory name to a part of key.
Definition at line 613 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.enc.
Referenced by de.zib.vold.backend.FileSystemDirectory.prefixlookup(), and de.zib.vold.backend.FileSystemDirectory.recursive_add().
String de.zib.vold.backend.FileSystemDirectory.buildfile (String dir) [private]
Convert the filename to a value.
Definition at line 582 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.enc.
Referenced by de.zib.vold.backend.FileSystemDirectory.file_add(), and de.zib.vold.backend.FileSystemDirectory.lookup().
void de.zib.vold.backend.FileSystemDirectory.checkState ()
Internal method which acts as part of the guard of all public methods.
Definition at line 111 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.rootPath.
Referenced by de.zib.vold.backend.FileSystemDirectory.open().
void de.zib.vold.backend.FileSystemDirectory.close ()
Close the database.
Note:
The annotation PreDestroy is used by the spring framework to call this method right before it will be destroyed.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 169 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.isopen(), de.zib.vold.backend.FileSystemDirectory.log, and de.zib.vold.backend.FileSystemDirectory.root.
Referenced by de.zib.vold.backend.FileSystemDirectory.open(), de.zib.vold.backend.FileSystemDirectory.setEnc(), and de.zib.vold.backend.FileSystemDirectory.setRootPath().
void de.zib.vold.backend.FileSystemDirectory.delete (int partition, List< String > key)
Delete the key and its values from a partition.
Parameters:
partition The partition to delete the key from.
key The key to delete.
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 283 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory._buildpath(), de.zib.vold.backend.FileSystemDirectory._get_partition_dir(), de.zib.vold.backend.FileSystemDirectory.isopen(), and de.zib.vold.backend.FileSystemDirectory.log.
void de.zib.vold.backend.FileSystemDirectory.file_add (List< String > key, String value, Map< List< String >, List< String > > map) [private]
Add a key with its values to the map.
Definition at line 510 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.buildfile().
Referenced by de.zib.vold.backend.FileSystemDirectory.prefixlookup(), and de.zib.vold.backend.FileSystemDirectory.recursive_add().
void de.zib.vold.backend.FileSystemDirectory.insert (int partition, List< String > key, List< String > value)
Insert a key with its set of values into a partition.
Note:
Already existing keys will be overwritten. This means especially, that all files in that directory will be deleted, before the new files will be created. Hence, no old values remain.
Parameters:
partition The partition to store the key in.
key The key to store.
param The values to store.
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 211 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory._buildfile(), de.zib.vold.backend.FileSystemDirectory._buildpath(), de.zib.vold.backend.FileSystemDirectory._get_partition_dir(), de.zib.vold.backend.FileSystemDirectory.isopen(), and de.zib.vold.backend.FileSystemDirectory.log.
boolean de.zib.vold.backend.FileSystemDirectory.isopen ()
Query the state of the database.
Returns:
true iff the database is open.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 188 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.root, and de.zib.vold.backend.FileSystemDirectory.rootPath.
Referenced by de.zib.vold.backend.FileSystemDirectory.close(), de.zib.vold.backend.FileSystemDirectory.delete(), de.zib.vold.backend.FileSystemDirectory.insert(), de.zib.vold.backend.FileSystemDirectory.lookup(), de.zib.vold.backend.FileSystemDirectory.open(), de.zib.vold.backend.FileSystemDirectory.prefixlookup(), de.zib.vold.backend.FileSystemDirectory.setEnc(), and de.zib.vold.backend.FileSystemDirectory.setRootPath().
List< String > de.zib.vold.backend.FileSystemDirectory.lookup (int partition, List< String > key)
Query the values for a key in a partition (root subdirectory).
Parameters:
partition The partition to search in.
key The key to search for.
Returns:
The set of values for that key.
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 344 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory._buildpath(), de.zib.vold.backend.FileSystemDirectory._get_partition_dir(), de.zib.vold.backend.FileSystemDirectory.buildfile(), de.zib.vold.backend.FileSystemDirectory.isopen(), and de.zib.vold.backend.FileSystemDirectory.log.
void de.zib.vold.backend.FileSystemDirectory.open ()
Open the database.
Note:
The annotation PostConstruct is used by the spring framework to call this method right after all properties have been set.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 128 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.checkState(), de.zib.vold.backend.FileSystemDirectory.close(), de.zib.vold.backend.FileSystemDirectory.isopen(), de.zib.vold.backend.FileSystemDirectory.log, de.zib.vold.backend.FileSystemDirectory.root, and de.zib.vold.backend.FileSystemDirectory.rootPath.
Map< List< String >, List< String > > de.zib.vold.backend.FileSystemDirectory.prefixlookup (int partition, List< String > key)
Query the entries with all keys beginning with a prefix.
Parameters:
partition The partition to search in.
prefix The prefix of the keys to search for.
Returns:
A map storing all results (mapping from a key to the set of values).
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 404 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory._builddir(), de.zib.vold.backend.FileSystemDirectory._buildpath(), de.zib.vold.backend.FileSystemDirectory._get_partition_dir(), de.zib.vold.backend.FileSystemDirectory.builddir(), de.zib.vold.backend.FileSystemDirectory.file_add(), de.zib.vold.backend.FileSystemDirectory.isopen(), de.zib.vold.backend.FileSystemDirectory.log, and de.zib.vold.backend.FileSystemDirectory.recursive_add().
void de.zib.vold.backend.FileSystemDirectory.recursive_add (List< String > key, String dir, Map< List< String >, List< String > > map) [private]
Recursively add all keys with its values to the map.
Definition at line 468 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.builddir(), de.zib.vold.backend.FileSystemDirectory.file_add(), and de.zib.vold.backend.FileSystemDirectory.log.
Referenced by de.zib.vold.backend.FileSystemDirectory.prefixlookup().
void de.zib.vold.backend.FileSystemDirectory.setEnc (String enc)
Set the encoding.
Note:
Setting the encoding while the database is open will result in closing it. It has to be opened again to use it afterwards.
Definition at line 96 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.close(), de.zib.vold.backend.FileSystemDirectory.enc, de.zib.vold.backend.FileSystemDirectory.isopen(), and de.zib.vold.backend.FileSystemDirectory.log.
void de.zib.vold.backend.FileSystemDirectory.setRootPath (String rootPath)
Set the root directory where to store the database.
Note:
Setting the root path while the database is open will result in closing it. It has to be opened again to use it afterwards.
Definition at line 78 of file FileSystemDirectory.java.
References de.zib.vold.backend.FileSystemDirectory.close(), de.zib.vold.backend.FileSystemDirectory.isopen(), de.zib.vold.backend.FileSystemDirectory.log, and de.zib.vold.backend.FileSystemDirectory.rootPath.
Member Data Documentation
String de.zib.vold.backend.FileSystemDirectory.enc = "utf-8" [private]
Definition at line 44 of file FileSystemDirectory.java.
Referenced by de.zib.vold.backend.FileSystemDirectory._builddir(), de.zib.vold.backend.FileSystemDirectory._buildfile(), de.zib.vold.backend.FileSystemDirectory.builddir(), de.zib.vold.backend.FileSystemDirectory.buildfile(), de.zib.vold.backend.FileSystemDirectory.FileSystemDirectory(), and de.zib.vold.backend.FileSystemDirectory.setEnc().
final Logger de.zib.vold.backend.FileSystemDirectory.log = LoggerFactory.getLogger(this.getClass()) [protected]
Definition at line 42 of file FileSystemDirectory.java.
Referenced by de.zib.vold.backend.FileSystemDirectory.close(), de.zib.vold.backend.FileSystemDirectory.delete(), de.zib.vold.backend.FileSystemDirectory.insert(), de.zib.vold.backend.FileSystemDirectory.lookup(), de.zib.vold.backend.FileSystemDirectory.open(), de.zib.vold.backend.FileSystemDirectory.prefixlookup(), de.zib.vold.backend.FileSystemDirectory.recursive_add(), de.zib.vold.backend.FileSystemDirectory.setEnc(), and de.zib.vold.backend.FileSystemDirectory.setRootPath().
File de.zib.vold.backend.FileSystemDirectory.root [private]
Definition at line 40 of file FileSystemDirectory.java.
Referenced by de.zib.vold.backend.FileSystemDirectory.close(), de.zib.vold.backend.FileSystemDirectory.FileSystemDirectory(), de.zib.vold.backend.FileSystemDirectory.isopen(), and de.zib.vold.backend.FileSystemDirectory.open().
String de.zib.vold.backend.FileSystemDirectory.rootPath [private]
Definition at line 41 of file FileSystemDirectory.java.
Referenced by de.zib.vold.backend.FileSystemDirectory._buildpath(), de.zib.vold.backend.FileSystemDirectory.checkState(), de.zib.vold.backend.FileSystemDirectory.FileSystemDirectory(), de.zib.vold.backend.FileSystemDirectory.isopen(), de.zib.vold.backend.FileSystemDirectory.open(), and de.zib.vold.backend.FileSystemDirectory.setRootPath().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/backend/FileSystemDirectory.java