VolD: de.zib.vold.replication.Replicator Interface Reference
de.zib.vold.replication.Replicator Interface Reference
Interface for replicators.
Public Member Functions
void refresh (List< String > key)
Replicate a refresh request.
void delete (List< String > key)
Replicate a delete request.
Package Functions
void insert (List< String > key, Set< String > value)
Replicate an insert request.
Detailed Description
Interface for replicators.
Replicators take a write request and send that to its associated VolatileDirectory.
Backends implementing this interface are used by the ReplicatedVolatileDirectory.
See also:
LocalReplicator
RESTReplicator
ReplicatedVolatileDirectory
Author:
Jörg Bachmann (bachmann@zib.de)
Definition at line 20 of file Replicator.java.
Member Function Documentation
void de.zib.vold.replication.Replicator.delete (List< String > key)
Replicate a delete request.
Parameters:
key The key to replicate the delete request for.
Implemented in de.zib.vold.replication.LocalReplicator, and de.zib.vold.replication.RESTVoldReplicator.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.delete().
void de.zib.vold.replication.Replicator.insert (List< String > key, Set< String > value) [package]
Replicate an insert request.
Parameters:
key The key to replicate the insert for.
value The values associated to the key.
Implemented in de.zib.vold.replication.LocalReplicator, and de.zib.vold.replication.RESTVoldReplicator.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.insert().
void de.zib.vold.replication.Replicator.refresh (List< String > key)
Replicate a refresh request.
Parameters:
key The key to replicate the refresh request for.
Implemented in de.zib.vold.replication.LocalReplicator, and de.zib.vold.replication.RESTVoldReplicator.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.refresh().
The documentation for this interface was generated from the following file:
server/src/main/java/de/zib/vold/replication/Replicator.java