VolD: de.zib.vold.backend.BabuDirectory Class Reference
de.zib.vold.backend.BabuDirectory Class Reference
Implementation of PartitionedDirectoryBackend based on BabuDB.
Public Member Functions
BabuDirectory (String basedir, String logdir, String sync, String databasename, String encoding)
Construct a BabuDirectory with all necessary informations.
BabuDirectory ()
Construct a BabuDirectory without initialization.
void setProperty (String key, String value)
Set a BabuDirectory property.
String getProperty (String key)
Get a BabuDirectory property.
void setDir (String dir)
Set the base directory BabuDB should use.
void setLogDir (String logDir)
Set the log directory BabuDB should use.
void setSync (String sync)
Set the sync method BabuDB should use.
void setDatabaseName (String databasename)
Set the database name for BabuDB.
void setEnc (String enc)
Set the encoding BabuDB should use.
void open ()
Open the database.
void close ()
Close the database.
boolean isopen ()
Query the state of the database.
void insert (int partition, List< String > key, List< String > value)
Insert a key with its set of values into a partition.
void delete (int partition, List< String > key)
Delete the key and its values from a partition.
Map< List< String >, List
< String > > prefixlookup (int partition, List< String > prefix)
Query the entries with all keys beginning with a prefix.
List< String > lookup (int partition, List< String > key)
Query the values for a key in a partition.
Protected Attributes
final Logger log = LoggerFactory.getLogger(this.getClass())
Private Member Functions
void insert (int partition, byte[] key, byte[] value)
Insert the key-value pair in a partition.
Map< byte[], byte[] > prefixlookup (int partition, byte[] key)
Query the values for all keys beginning with a prefix in a partition.
byte[] lookup (int partition, byte[] key)
Query the value for a key in the given table.
byte[] _buildkey (List< String > l)
Convert a directory (interface language) to a byte array (backend language).
List< String > buildkey (byte[] _key)
Convert a byte array (backend language) to a directory (interface language).
void byteCopy (byte[] dest, byte[] src, int offset)
C-Style memcpy whereas the length is given by the src array.
Private Attributes
Properties props
String dbname
String enc
BabuDB babudb
Database db
boolean opened
Detailed Description
Implementation of PartitionedDirectoryBackend based on BabuDB.
Since this class implements a PartitionedDirectory and BabuDB only knows about byte arrays, the directories need to be transformed. This is done by joining the directory structere with a null byte as delimiter. The same will be done for the values of a key (i.e. of a directory). All values of a set are joined into one byte array using a null byte as delimiter.
See also:
PartitionedDirectoryBackend
org.xtreemfs.babudb
Author:
Jörg Bachmann (bachmann@zib.de)
Definition at line 43 of file BabuDirectory.java.
Constructor & Destructor Documentation
de.zib.vold.backend.BabuDirectory.BabuDirectory (String basedir, String logdir, String sync, String databasename, String encoding)
Construct a BabuDirectory with all necessary informations.
Note:
This constructor will not open the interface. This still has to be done using the open method.
Parameters:
basedir The directory, where the BabuDB is stored.
logdir The directory, where all logfiles of BabuDB are stored.
sync The sync method used in BabuDB. Usual values are ASYNC and FSYNC.
encoding The encoding which will be used.
Definition at line 68 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.dbname, de.zib.vold.backend.BabuDirectory.enc, de.zib.vold.backend.BabuDirectory.opened, and de.zib.vold.backend.BabuDirectory.props.
de.zib.vold.backend.BabuDirectory.BabuDirectory ()
Construct a BabuDirectory without initialization.
Definition at line 85 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.dbname, de.zib.vold.backend.BabuDirectory.enc, de.zib.vold.backend.BabuDirectory.opened, and de.zib.vold.backend.BabuDirectory.props.
Member Function Documentation
byte [] de.zib.vold.backend.BabuDirectory._buildkey (List< String > l) [private]
Convert a directory (interface language) to a byte array (backend language).
Parameters:
l The directory to transform to lower level.
Returns:
The byte array which can be used in BabuDB.
Exceptions:
VoldException
Definition at line 606 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.byteCopy(), and de.zib.vold.backend.BabuDirectory.enc.
Referenced by de.zib.vold.backend.BabuDirectory.delete(), de.zib.vold.backend.BabuDirectory.insert(), de.zib.vold.backend.BabuDirectory.lookup(), and de.zib.vold.backend.BabuDirectory.prefixlookup().
List< String > de.zib.vold.backend.BabuDirectory.buildkey (byte[] _key) [private]
Convert a byte array (backend language) to a directory (interface language).
Parameters:
_key The key to transform to higher level.
Returns:
The directory.
Exceptions:
VoldException
Definition at line 681 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.enc.
Referenced by de.zib.vold.backend.BabuDirectory.lookup(), and de.zib.vold.backend.BabuDirectory.prefixlookup().
void de.zib.vold.backend.BabuDirectory.byteCopy (byte[] dest, byte[] src, int offset) [private]
C-Style memcpy whereas the length is given by the src array.
Exceptions:
IllegalArgumentException
Definition at line 716 of file BabuDirectory.java.
Referenced by de.zib.vold.backend.BabuDirectory._buildkey().
void de.zib.vold.backend.BabuDirectory.close ()
Close the database.
Note:
The annotation PreDestroy is used by the spring framework to call this method right before it will be destroyed.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 279 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.babudb, de.zib.vold.backend.BabuDirectory.isopen(), de.zib.vold.backend.BabuDirectory.log, and de.zib.vold.backend.BabuDirectory.opened.
void de.zib.vold.backend.BabuDirectory.delete (int partition, List< String > key)
Delete the key and its values from a partition.
Parameters:
partition The partition to delete the key from.
key The key to delete.
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 370 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory._buildkey(), de.zib.vold.backend.BabuDirectory.insert(), de.zib.vold.backend.BabuDirectory.isopen(), and de.zib.vold.backend.BabuDirectory.log.
String de.zib.vold.backend.BabuDirectory.getProperty (String key)
Get a BabuDirectory property.
Parameters:
key The property to query
Definition at line 115 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.props.
Referenced by de.zib.vold.backend.BabuDirectory.open().
void de.zib.vold.backend.BabuDirectory.insert (int partition, List< String > key, List< String > value)
Insert a key with its set of values into a partition.
Note:
Already existing keys will be overwritten.
Parameters:
partition The partition to store the key in.
key The key to store.
param The values to store.
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 331 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory._buildkey(), de.zib.vold.backend.BabuDirectory.isopen(), and de.zib.vold.backend.BabuDirectory.log.
Referenced by de.zib.vold.backend.BabuDirectory.delete().
void de.zib.vold.backend.BabuDirectory.insert (int partition, byte[] key, byte[] value) [private]
Insert the key-value pair in a partition.
Parameters:
partition The partition to store the pair in.
key The key to store.
value The value to store.
Definition at line 459 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.db.
boolean de.zib.vold.backend.BabuDirectory.isopen ()
Query the state of the database.
Returns:
true iff the database is open.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 314 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.opened.
Referenced by de.zib.vold.backend.BabuDirectory.close(), de.zib.vold.backend.BabuDirectory.delete(), de.zib.vold.backend.BabuDirectory.insert(), de.zib.vold.backend.BabuDirectory.lookup(), de.zib.vold.backend.BabuDirectory.open(), and de.zib.vold.backend.BabuDirectory.prefixlookup().
byte [] de.zib.vold.backend.BabuDirectory.lookup (int partition, byte[] key) [private]
Query the value for a key in the given table.
The query will be performed synchronously.
Parameters:
partition The partition to search in.
key The key to search for.
Returns:
null if the key was not found and otherwise the value.
Exceptions:
VoldException
Definition at line 579 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.db.
List< String > de.zib.vold.backend.BabuDirectory.lookup (int partition, List< String > key)
Query the values for a key in a partition.
The query will be performed synchronously.
Parameters:
partition The partition to search in.
key The key to search for.
Returns:
The set of values for that key.
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 542 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory._buildkey(), de.zib.vold.backend.BabuDirectory.buildkey(), de.zib.vold.backend.BabuDirectory.isopen(), and de.zib.vold.backend.BabuDirectory.log.
void de.zib.vold.backend.BabuDirectory.open ()
Open the database.
Note:
The annotation PostConstruct is used by the spring framework to call this method right after all properties have been set.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 204 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.babudb, de.zib.vold.backend.BabuDirectory.db, de.zib.vold.backend.BabuDirectory.dbname, de.zib.vold.backend.BabuDirectory.getProperty(), de.zib.vold.backend.BabuDirectory.isopen(), de.zib.vold.backend.BabuDirectory.log, de.zib.vold.backend.BabuDirectory.opened, and de.zib.vold.backend.BabuDirectory.props.
Map< List< String >, List< String > > de.zib.vold.backend.BabuDirectory.prefixlookup (int partition, List< String > prefix)
Query the entries with all keys beginning with a prefix.
Parameters:
partition The partition to search in.
prefix The prefix of the keys to search for.
Returns:
A map storing all results (mapping from a key to the set of values).
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 408 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory._buildkey(), de.zib.vold.backend.BabuDirectory.buildkey(), de.zib.vold.backend.BabuDirectory.isopen(), and de.zib.vold.backend.BabuDirectory.log.
Map< byte[], byte[] > de.zib.vold.backend.BabuDirectory.prefixlookup (int partition, byte[] key) [private]
Query the values for all keys beginning with a prefix in a partition.
The query will be performed synchronously.
Parameters:
partition The partition to search in.
key The prefix of the keys to search for.
Returns:
All found results, i.e. a map from all found keys to its values.
Exceptions:
VoldException
Definition at line 488 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.db.
void de.zib.vold.backend.BabuDirectory.setDatabaseName (String databasename)
Set the database name for BabuDB.
Since BabuDB is capable of storing different databases, a database name need to be given. When sharing the BabuDB instance (base directory and log directory) with other processes, database names should be unique.
Note:
This is an essential property.
Parameters:
dir The database name for the BabuDB internal database.
Definition at line 176 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.dbname.
void de.zib.vold.backend.BabuDirectory.setDir (String dir)
Set the base directory BabuDB should use.
Note:
This is an essential property.
Parameters:
dir The base directory for BabuDB.
Definition at line 127 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.setProperty().
void de.zib.vold.backend.BabuDirectory.setEnc (String enc)
Set the encoding BabuDB should use.
Nowadays, "utf-8" is a common setting.
Note:
This is an essential property.
Parameters:
dir The encoding for BabuDB.
Definition at line 190 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.enc.
void de.zib.vold.backend.BabuDirectory.setLogDir (String logDir)
Set the log directory BabuDB should use.
Note:
This is an essential property.
Parameters:
dir The log directroy for BabuDB.
Definition at line 139 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.setProperty().
void de.zib.vold.backend.BabuDirectory.setProperty (String key, String value)
Set a BabuDirectory property.
Note:
If the babudirectoy is already opened, the properties will only take effect on restart (close and immediate open).
Parameters:
key The property to set.
value The value for the property.
Definition at line 105 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.props.
Referenced by de.zib.vold.backend.BabuDirectory.setDir(), de.zib.vold.backend.BabuDirectory.setLogDir(), and de.zib.vold.backend.BabuDirectory.setSync().
void de.zib.vold.backend.BabuDirectory.setSync (String sync)
Set the sync method BabuDB should use.
Possible values are ASYNC, FDATASYNC, FSYNC, SYNC_WRITE and SYNC_WRITE_METADATA.
ASYNC: asynchronously write log entries (data is lost when system crashes).
FDATASYNC: TODO: not documented in BabuDB
FSYNC: executes an fsync on the logfile before acknowledging the operation.
SYNC_WRITE: synchronously writes the log entry to disk before ack.
SYNC_WRITE_METADATA: synchronously writes the log entry to disk and updates the metadata before ack.
Note:
This is an essential property.
Parameters:
dir The sync method for BabuDB.
Definition at line 159 of file BabuDirectory.java.
References de.zib.vold.backend.BabuDirectory.setProperty().
Member Data Documentation
BabuDB de.zib.vold.backend.BabuDirectory.babudb [private]
Definition at line 50 of file BabuDirectory.java.
Referenced by de.zib.vold.backend.BabuDirectory.close(), and de.zib.vold.backend.BabuDirectory.open().
Database de.zib.vold.backend.BabuDirectory.db [private]
Definition at line 51 of file BabuDirectory.java.
Referenced by de.zib.vold.backend.BabuDirectory.insert(), de.zib.vold.backend.BabuDirectory.lookup(), de.zib.vold.backend.BabuDirectory.open(), and de.zib.vold.backend.BabuDirectory.prefixlookup().
String de.zib.vold.backend.BabuDirectory.dbname [private]
Definition at line 46 of file BabuDirectory.java.
Referenced by de.zib.vold.backend.BabuDirectory.BabuDirectory(), de.zib.vold.backend.BabuDirectory.open(), and de.zib.vold.backend.BabuDirectory.setDatabaseName().
String de.zib.vold.backend.BabuDirectory.enc [private]
Definition at line 48 of file BabuDirectory.java.
Referenced by de.zib.vold.backend.BabuDirectory._buildkey(), de.zib.vold.backend.BabuDirectory.BabuDirectory(), de.zib.vold.backend.BabuDirectory.buildkey(), and de.zib.vold.backend.BabuDirectory.setEnc().
final Logger de.zib.vold.backend.BabuDirectory.log = LoggerFactory.getLogger(this.getClass()) [protected]
Definition at line 54 of file BabuDirectory.java.
Referenced by de.zib.vold.backend.BabuDirectory.close(), de.zib.vold.backend.BabuDirectory.delete(), de.zib.vold.backend.BabuDirectory.insert(), de.zib.vold.backend.BabuDirectory.lookup(), de.zib.vold.backend.BabuDirectory.open(), and de.zib.vold.backend.BabuDirectory.prefixlookup().
boolean de.zib.vold.backend.BabuDirectory.opened [private]
Definition at line 52 of file BabuDirectory.java.
Referenced by de.zib.vold.backend.BabuDirectory.BabuDirectory(), de.zib.vold.backend.BabuDirectory.close(), de.zib.vold.backend.BabuDirectory.isopen(), and de.zib.vold.backend.BabuDirectory.open().
Properties de.zib.vold.backend.BabuDirectory.props [private]
Definition at line 45 of file BabuDirectory.java.
Referenced by de.zib.vold.backend.BabuDirectory.BabuDirectory(), de.zib.vold.backend.BabuDirectory.getProperty(), de.zib.vold.backend.BabuDirectory.open(), and de.zib.vold.backend.BabuDirectory.setProperty().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/backend/BabuDirectory.java