VolD: de.zib.vold.backend.PartitionedDirectory Interface Reference
de.zib.vold.backend.PartitionedDirectory Interface Reference
Interface for directory backends usage.
Public Member Functions
void delete (int partition, List< String > key)
Delete a key.
List< String > lookup (int partition, List< String > key)
Query the contents of a key.
Map< List< String >, List
< String > > prefixlookup (int partition, List< String > prefix)
Query the contents of all keys starting with the given prefix.
Package Functions
void insert (int partition, List< String > key, List< String > value)
Insert a set of values for a given key.
Detailed Description
Interface for directory backends usage.
A partitioned directory offers the possibility to store a set of values in a certain directory of a certain partition. The content of a single directory (key) can then be queried. Furthermore, the content of all directories starting with a given prefix can be queried.
Backends implementing this interface are used by the VolatileDirectory
Note:
Although the values are given in lists, some implementations have a set semantic here.
The two words key and directory are used as synonyms here.
See also:
PartitionedDirectoryBackend
BabuDirectory
FileSystemDirectory
LoggerDirectory
VolatileDirectory
Author:
Jörg Bachmann (bachmann@zib.de)
Definition at line 29 of file PartitionedDirectory.java.
Member Function Documentation
void de.zib.vold.backend.PartitionedDirectory.delete (int partition, List< String > key)
Delete a key.
Parameters:
partition The partition to store the value in.
key The key to delete in the partition.
Implemented in de.zib.vold.backend.BabuDirectory, de.zib.vold.backend.FileSystemDirectory, and de.zib.vold.backend.WriteLogger.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh().
void de.zib.vold.backend.PartitionedDirectory.insert (int partition, List< String > key, List< String > value) [package]
Insert a set of values for a given key.
Note:
Negative partitions are not allowed!
Parameters:
partition The partition to store the value in.
key The key to store in the partition.
value The values to store for the key.
Implemented in de.zib.vold.backend.BabuDirectory, de.zib.vold.backend.FileSystemDirectory, and de.zib.vold.backend.WriteLogger.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh().
List< String > de.zib.vold.backend.PartitionedDirectory.lookup (int partition, List< String > key)
Query the contents of a key.
Parameters:
partition The partition to store the value in.
key The key to query in the partition.
Implemented in de.zib.vold.backend.BabuDirectory, de.zib.vold.backend.FileSystemDirectory, and de.zib.vold.backend.WriteLogger.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.lookup(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh().
Map< List< String >, List< String > > de.zib.vold.backend.PartitionedDirectory.prefixlookup (int partition, List< String > prefix)
Query the contents of all keys starting with the given prefix.
Note:
Using the prefix AA/BB will even find contents of the prefix AA/BBBBBB/CCCC.
Parameters:
partition The partition to store the value in.
prefix The prefix of the keys to query in the partition.
Implemented in de.zib.vold.backend.BabuDirectory, de.zib.vold.backend.FileSystemDirectory, and de.zib.vold.backend.WriteLogger.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.prefixLookup(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.sliceLookup().
The documentation for this interface was generated from the following file:
server/src/main/java/de/zib/vold/backend/PartitionedDirectory.java