VolD: de.zib.vold.backend.WriteLogger Class Reference
de.zib.vold.backend.WriteLogger Class Reference
Incomplete implementation of PartitionedDirectoryBackend which serves as logfile.
Public Member Functions
WriteLogger (String logfilename)
Construct a WriteLogger with all necessary informations.
WriteLogger ()
Construct a BabuDirectory without initialization.
void setLogfile (String logfilename)
Set the path to the logfile.
void checkState ()
Internal method which acts as part of the guard of all public methods.
void open ()
Open the database.
void close ()
Close the database.
boolean isopen ()
Query the state of the database.
void insert (int partition, List< String > key, List< String > value)
Log the request for an insert.
void delete (int partition, List< String > key)
Log a request for a delete.
List< String > lookup (int partition, List< String > key)
Not implemented.
Map< List< String >, List
< String > > prefixlookup (int partition, List< String > key)
Not implemented.
Protected Attributes
final Logger log = LoggerFactory.getLogger(this.getClass())
Private Attributes
String logfilename
FileWriter logfile
BufferedWriter out
Detailed Description
Incomplete implementation of PartitionedDirectoryBackend which serves as logfile.
This backend simply log all write requests on the database to a single logfile.
See also:
PartitionedDirectoryBackend
Author:
Jörg Bachmann (bachmann@zib.de)
Definition at line 28 of file WriteLogger.java.
Constructor & Destructor Documentation
de.zib.vold.backend.WriteLogger.WriteLogger (String logfilename)
Construct a WriteLogger with all necessary informations.
Note:
This constructor will not open the interface. This still has to be done using the open method.
Parameters:
logfilename The path to the logfile.
Definition at line 44 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.logfile, de.zib.vold.backend.WriteLogger.logfilename, and de.zib.vold.backend.WriteLogger.out.
de.zib.vold.backend.WriteLogger.WriteLogger ()
Construct a BabuDirectory without initialization.
Definition at line 55 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.logfile, de.zib.vold.backend.WriteLogger.logfilename, and de.zib.vold.backend.WriteLogger.out.
Member Function Documentation
void de.zib.vold.backend.WriteLogger.checkState ()
Internal method which acts as part of the guard of all public methods.
Definition at line 88 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.logfilename.
Referenced by de.zib.vold.backend.WriteLogger.close(), de.zib.vold.backend.WriteLogger.delete(), de.zib.vold.backend.WriteLogger.insert(), and de.zib.vold.backend.WriteLogger.open().
void de.zib.vold.backend.WriteLogger.close ()
Close the database.
Note:
The annotation PreDestroy is used by the spring framework to call this method right before it will be destroyed.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 142 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.checkState(), de.zib.vold.backend.WriteLogger.isopen(), de.zib.vold.backend.WriteLogger.log, de.zib.vold.backend.WriteLogger.logfile, and de.zib.vold.backend.WriteLogger.out.
void de.zib.vold.backend.WriteLogger.delete (int partition, List< String > key)
Log a request for a delete.
Parameters:
partition The partition to delete the key from.
key The key to delete.
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 231 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.checkState(), de.zib.vold.backend.WriteLogger.isopen(), de.zib.vold.backend.WriteLogger.log, and de.zib.vold.backend.WriteLogger.out.
void de.zib.vold.backend.WriteLogger.insert (int partition, List< String > key, List< String > value)
Log the request for an insert.
Parameters:
partition The partition to store the key in.
key The key to store.
param The values to store.
Exceptions:
VoldException
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 197 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.checkState(), de.zib.vold.backend.WriteLogger.isopen(), de.zib.vold.backend.WriteLogger.log, and de.zib.vold.backend.WriteLogger.out.
boolean de.zib.vold.backend.WriteLogger.isopen ()
Query the state of the database.
Returns:
true iff the logfile is set and open.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 182 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.logfile, and de.zib.vold.backend.WriteLogger.out.
Referenced by de.zib.vold.backend.WriteLogger.close(), de.zib.vold.backend.WriteLogger.delete(), de.zib.vold.backend.WriteLogger.insert(), de.zib.vold.backend.WriteLogger.open(), and de.zib.vold.backend.WriteLogger.setLogfile().
List< String > de.zib.vold.backend.WriteLogger.lookup (int partition, List< String > key)
Not implemented.
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 260 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.log.
void de.zib.vold.backend.WriteLogger.open ()
Open the database.
Note:
The annotation PostConstruct is used by the spring framework to call this method right after all properties have been set.
Implements de.zib.vold.backend.PartitionedDirectoryBackend.
Definition at line 105 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.checkState(), de.zib.vold.backend.WriteLogger.isopen(), de.zib.vold.backend.WriteLogger.log, de.zib.vold.backend.WriteLogger.logfile, de.zib.vold.backend.WriteLogger.logfilename, and de.zib.vold.backend.WriteLogger.out.
Map< List< String >, List< String > > de.zib.vold.backend.WriteLogger.prefixlookup (int partition, List< String > key)
Not implemented.
Implements de.zib.vold.backend.PartitionedDirectory.
Definition at line 274 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.log.
void de.zib.vold.backend.WriteLogger.setLogfile (String logfilename)
Set the path to the logfile.
Note:
If the writelogger is already opened, the properties will only take effect on restart (close and immediate open).
Parameters:
logfilename The path to the logfile.
Definition at line 72 of file WriteLogger.java.
References de.zib.vold.backend.WriteLogger.isopen(), de.zib.vold.backend.WriteLogger.log, and de.zib.vold.backend.WriteLogger.logfilename.
Member Data Documentation
final Logger de.zib.vold.backend.WriteLogger.log = LoggerFactory.getLogger(this.getClass()) [protected]
Definition at line 30 of file WriteLogger.java.
Referenced by de.zib.vold.backend.WriteLogger.close(), de.zib.vold.backend.WriteLogger.delete(), de.zib.vold.backend.WriteLogger.insert(), de.zib.vold.backend.WriteLogger.lookup(), de.zib.vold.backend.WriteLogger.open(), de.zib.vold.backend.WriteLogger.prefixlookup(), and de.zib.vold.backend.WriteLogger.setLogfile().
FileWriter de.zib.vold.backend.WriteLogger.logfile [private]
Definition at line 33 of file WriteLogger.java.
Referenced by de.zib.vold.backend.WriteLogger.close(), de.zib.vold.backend.WriteLogger.isopen(), de.zib.vold.backend.WriteLogger.open(), and de.zib.vold.backend.WriteLogger.WriteLogger().
String de.zib.vold.backend.WriteLogger.logfilename [private]
Definition at line 32 of file WriteLogger.java.
Referenced by de.zib.vold.backend.WriteLogger.checkState(), de.zib.vold.backend.WriteLogger.open(), de.zib.vold.backend.WriteLogger.setLogfile(), and de.zib.vold.backend.WriteLogger.WriteLogger().
BufferedWriter de.zib.vold.backend.WriteLogger.out [private]
Definition at line 34 of file WriteLogger.java.
Referenced by de.zib.vold.backend.WriteLogger.close(), de.zib.vold.backend.WriteLogger.delete(), de.zib.vold.backend.WriteLogger.insert(), de.zib.vold.backend.WriteLogger.isopen(), de.zib.vold.backend.WriteLogger.open(), and de.zib.vold.backend.WriteLogger.WriteLogger().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/backend/WriteLogger.java