VolD: de.zib.vold.volatilelogic.VolatileDirectoryImpl Class Reference
de.zib.vold.volatilelogic.VolatileDirectoryImpl Class Reference
Implementation of the volatile directory logic.
Public Member Functions
VolatileDirectoryImpl (PartitionedDirectory backend, TimeSlice timeslice)
Construct a VolatileDirectoryImpl.
VolatileDirectoryImpl ()
Construct an uninitialized VolatileDirectoryImpl.
void setTimeslice (TimeSlice timeslice)
Set the timeslice configuration.
void setBackend (PartitionedDirectory backend)
Set the backend used to store all informations.
long getActualSlice ()
A delegator for TimeSlice.getActualSlice().
long getNumberOfSlices ()
A delegator for TimeSlice.getNumberOfSlices().
long getTimeSliceSize ()
A delegator for TimeSlice.getTimeSliceSize().
void insert (List< String > key, Set< String > value)
Insert a key with its set of values.
void refresh (List< String > key)
Refresh a key.
void delete (List< String > key)
Delete a key.
Set< String > lookup (List< String > key)
Query the values for a key.
Map< List< String >, Set
< String > > prefixLookup (List< String > key)
Query all keys beginning with a certain prefix.
Map< List< String >, DateTime > sliceLookup (long slice)
Query all keys in a certain time slice.
Protected Member Functions
void checkState ()
Internal method which acts as part of the guard of all public methods.
Protected Attributes
final Logger log = LoggerFactory.getLogger(this.getClass())
Private Member Functions
DateTime to_date (List< String > date)
Convert a date value to a DateTime object.
List< String > to_date (DateTime date)
Convert a time to a value.
long to_timeslice (List< String > slice)
Convert a key holding a timeslice only to a timeslice.
List< String > get_timeslice_key (long slice, List< String > key)
Melt a timeslice and key to a complete key.
List< String > to_value (long slice)
Convert a timeslice to a key.
Private Attributes
PartitionedDirectory directory
TimeSlice timeslice
Detailed Description
Implementation of the volatile directory logic.
The purpose of this class is the correct storage of a key in the backend in such a way, that each key always holds its timestamp. This timestamp is the time of the last write request (which is an insert and a refresh). Furthermore these timestamps will be deleted too, when the according keys are deleted.
Using the backend, three partitions will be used.
a "key - value" partition storing all key value pairs
a "key - timeslice" partition
a "slice/key - date" partition
The last partition is used by the Reaper to request all keys in a certain timeslice an check their age. The second partition is used to determine the "slice/key - date" entry when a key is deleted.
See also:
VolatileDirectory
PartitionedDirectory
Author:
Jörg Bachmann (bachmann@zib.de)
Definition at line 42 of file VolatileDirectoryImpl.java.
Constructor & Destructor Documentation
de.zib.vold.volatilelogic.VolatileDirectoryImpl.VolatileDirectoryImpl (PartitionedDirectory backend, TimeSlice timeslice)
Construct a VolatileDirectoryImpl.
Parameters:
backend The backend used to store the keys.
timeslice The timeslice configuration.
Definition at line 55 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice.
de.zib.vold.volatilelogic.VolatileDirectoryImpl.VolatileDirectoryImpl ()
Construct an uninitialized VolatileDirectoryImpl.
Definition at line 64 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice.
Member Function Documentation
void de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState () [protected]
Internal method which acts as part of the guard of all public methods.
Definition at line 73 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.getActualSlice(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.getNumberOfSlices(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.getTimeSliceSize(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.lookup(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.prefixLookup(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.sliceLookup().
void de.zib.vold.volatilelogic.VolatileDirectoryImpl.delete (List< String > key)
Delete a key.
Deleting the key means deleting the "key -- value" entry, the "key -- timeslice" entry and the "slice/key -- date" entry.
Parameters:
key The key to delete.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 307 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.backend.PartitionedDirectory.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, de.zib.vold.volatilelogic.VolatileDirectoryImpl.get_timeslice_key(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.log, de.zib.vold.backend.PartitionedDirectory.lookup(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_timeslice().
List< String > de.zib.vold.volatilelogic.VolatileDirectoryImpl.get_timeslice_key (long slice, List< String > key) [private]
Melt a timeslice and key to a complete key.
The timeslice will be prepended to the key using to_value.
Parameters:
timeslice The timeslice to prepend.
key The key which will be completed.
Returns:
The complete key.
See also:
to_value
Definition at line 526 of file VolatileDirectoryImpl.java.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.sliceLookup().
long de.zib.vold.volatilelogic.VolatileDirectoryImpl.getActualSlice ()
A delegator for TimeSlice.getActualSlice().
See also:
TimeSlice
Implements de.zib.vold.volatilelogic.SlicedDirectory.
Definition at line 110 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.volatilelogic.TimeSlice.getActualSlice(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice.
long de.zib.vold.volatilelogic.VolatileDirectoryImpl.getNumberOfSlices ()
A delegator for TimeSlice.getNumberOfSlices().
See also:
TimeSlice
Implements de.zib.vold.volatilelogic.SlicedDirectory.
Definition at line 126 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.volatilelogic.TimeSlice.getNumberOfSlices(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice.
long de.zib.vold.volatilelogic.VolatileDirectoryImpl.getTimeSliceSize ()
A delegator for TimeSlice.getTimeSliceSize().
See also:
TimeSlice
Implements de.zib.vold.volatilelogic.SlicedDirectory.
Definition at line 142 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.volatilelogic.TimeSlice.getTimeSliceSize(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice.
void de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert (List< String > key, Set< String > value)
Insert a key with its set of values.
The method for inserting the key works as follows: 1. insert the new "slice/key -- date" entry 2. insert "key -- timeslice" entry 3. insert "key -- value" entry 4. delete old "slice/key -- date" entry (when existant)
Parameters:
key The key to insert.
value The values associated to the key.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 165 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.backend.PartitionedDirectory.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, de.zib.vold.volatilelogic.VolatileDirectoryImpl.get_timeslice_key(), de.zib.vold.volatilelogic.TimeSlice.getActualSlice(), de.zib.vold.backend.PartitionedDirectory.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.log, de.zib.vold.backend.PartitionedDirectory.lookup(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice, de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_date(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_timeslice(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_value().
Set< String > de.zib.vold.volatilelogic.VolatileDirectoryImpl.lookup (List< String > key)
Query the values for a key.
Returns:
null if the key could not be found and the set of values otherwise.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 348 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, de.zib.vold.volatilelogic.VolatileDirectoryImpl.log, and de.zib.vold.backend.PartitionedDirectory.lookup().
Map< List< String >, Set< String > > de.zib.vold.volatilelogic.VolatileDirectoryImpl.prefixLookup (List< String > key)
Query all keys beginning with a certain prefix.
Parameters:
key The prefix of the keys to be returned.
Returns:
The map of all found keys and its associated values.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 371 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, de.zib.vold.volatilelogic.VolatileDirectoryImpl.log, and de.zib.vold.backend.PartitionedDirectory.prefixlookup().
void de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh (List< String > key)
Refresh a key.
This method resets the timestamp of the key to the actual time and also resets the timeslice.
The method for refreshing the key works similar to VolatileDirectorImpl.insert(..): 1. insert the new "slice/key -- date" entry 2. insert "key -- timeslice" entry 3. delete old "slice/key -- date" entry (when existant) The only difference is, that there is no need to insert the key/date entry, since it had already been inserted.
Parameters:
key The key to refresh.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 244 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.backend.PartitionedDirectory.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, de.zib.vold.volatilelogic.VolatileDirectoryImpl.get_timeslice_key(), de.zib.vold.volatilelogic.TimeSlice.getActualSlice(), de.zib.vold.backend.PartitionedDirectory.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.log, de.zib.vold.backend.PartitionedDirectory.lookup(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice, de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_date(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_timeslice(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_value().
void de.zib.vold.volatilelogic.VolatileDirectoryImpl.setBackend (PartitionedDirectory backend)
Set the backend used to store all informations.
Definition at line 99 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory.
void de.zib.vold.volatilelogic.VolatileDirectoryImpl.setTimeslice (TimeSlice timeslice)
Set the timeslice configuration.
Parameters:
timeslice The TimeSlice used by all write requests to determine the actual timeslice.
Definition at line 86 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.log, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice.
Map< List< String >, DateTime > de.zib.vold.volatilelogic.VolatileDirectoryImpl.sliceLookup (long slice)
Query all keys in a certain time slice.
Parameters:
slice The time slice to query all key--date pairs for.
Returns:
A map of all "key -- date" entries of that slice.
Implements de.zib.vold.volatilelogic.SlicedDirectory.
Definition at line 404 of file VolatileDirectoryImpl.java.
References de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory, de.zib.vold.volatilelogic.VolatileDirectoryImpl.get_timeslice_key(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.log, de.zib.vold.backend.PartitionedDirectory.prefixlookup(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_date().
List< String > de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_date (DateTime date) [private]
Convert a time to a value.
Parameters:
date The date to convert.
Returns:
The value holding the date.
Definition at line 490 of file VolatileDirectoryImpl.java.
DateTime de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_date (List< String > date) [private]
Convert a date value to a DateTime object.
Parameters:
date The date value.
Returns:
The according DateTime object.
Note:
The date value may only have exactly one element!
Exceptions:
NumberFormatException
Definition at line 474 of file VolatileDirectoryImpl.java.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.sliceLookup().
long de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_timeslice (List< String > slice) [private]
Convert a key holding a timeslice only to a timeslice.
Parameters:
slice The key holding the slice.
Returns:
The timeslice extracted out of the key.
Note:
The key may only have exactly one element!
Definition at line 505 of file VolatileDirectoryImpl.java.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh().
List< String > de.zib.vold.volatilelogic.VolatileDirectoryImpl.to_value (long slice) [private]
Convert a timeslice to a key.
Parameters:
slice The timeslice to convert.
Returns:
The key containing the slice as first and only element.
Definition at line 545 of file VolatileDirectoryImpl.java.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh().
Member Data Documentation
PartitionedDirectory de.zib.vold.volatilelogic.VolatileDirectoryImpl.directory [private]
Definition at line 44 of file VolatileDirectoryImpl.java.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.lookup(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.prefixLookup(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.setBackend(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.sliceLookup(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.VolatileDirectoryImpl().
final Logger de.zib.vold.volatilelogic.VolatileDirectoryImpl.log = LoggerFactory.getLogger(this.getClass()) [protected]
Definition at line 47 of file VolatileDirectoryImpl.java.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.delete(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.lookup(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.prefixLookup(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.setTimeslice(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.sliceLookup().
TimeSlice de.zib.vold.volatilelogic.VolatileDirectoryImpl.timeslice [private]
Definition at line 45 of file VolatileDirectoryImpl.java.
Referenced by de.zib.vold.volatilelogic.VolatileDirectoryImpl.checkState(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.getActualSlice(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.getNumberOfSlices(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.getTimeSliceSize(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.insert(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.refresh(), de.zib.vold.volatilelogic.VolatileDirectoryImpl.setTimeslice(), and de.zib.vold.volatilelogic.VolatileDirectoryImpl.VolatileDirectoryImpl().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/volatilelogic/VolatileDirectoryImpl.java