VolD: de.zib.vold.volatilelogic.SlicedDirectory Interface Reference
de.zib.vold.volatilelogic.SlicedDirectory Interface Reference
Interface for Backends with slice information.
Public Member Functions
long getTimeSliceSize ()
Get the size of one slice in milliseconds.
long getNumberOfSlices ()
Get the number of slices.
void delete (List< String > key)
Delete a key.
Map< List< String >, DateTime > sliceLookup (long timeslice)
Query for all Key-insertiontime pairs of a given timeslice.
Package Functions
long getActualSlice ()
Returns the slice number for the actual time.
Detailed Description
Interface for Backends with slice information.
For each entry the timeslice of the time of the insertion will be remembered, thus the map of key-valuelists can be returned within a given timeslice.
Each slice has the same size (given in seconds). The slice room is a factor ring. The actual slice number is calculated by the actual time by dividing it by timeslicesize and taking the first representative in the ring mod numberofslices. Hence, the slice is a number between 0 and numberofslices-1.
See also:
VolatileDirectory
Reaper
Author:
Jörg Bachmann (bachmann@zib.de)
Definition at line 24 of file SlicedDirectory.java.
Member Function Documentation
void de.zib.vold.volatilelogic.SlicedDirectory.delete (List< String > key)
Delete a key.
Note:
Since this interface is used by the Reaper and the Reaper needs to delete keys, the interface requires this method although the SimpleDirectory provides this method too. When changing its signature, the signature should also be changed in SimpleDirectory.
Parameters:
key The key to delete.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.replication.LocalReplicator.delete(), de.zib.vold.frontend.Frontend.delete(), de.zib.vold.frontend.Reaper.ReaperWorker.reap_timeslice(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.DeleteThread.run().
long de.zib.vold.volatilelogic.SlicedDirectory.getActualSlice () [package]
Returns the slice number for the actual time.
Returns:
The actual slice number.
Note:
The slice number may no more be actual on return.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getActualSlice(), and de.zib.vold.frontend.Reaper.reap().
long de.zib.vold.volatilelogic.SlicedDirectory.getNumberOfSlices ()
Get the number of slices.
Each slice number will be returned modulo this number.
Returns:
The number of slices in this SlicedDirectory.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getNumberOfSlices().
long de.zib.vold.volatilelogic.SlicedDirectory.getTimeSliceSize ()
Get the size of one slice in milliseconds.
Returns:
The time slice size in milliseconds.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getTimeSliceSize(), and de.zib.vold.frontend.Reaper.reap().
Map< List< String >, DateTime> de.zib.vold.volatilelogic.SlicedDirectory.sliceLookup (long timeslice)
Query for all Key-insertiontime pairs of a given timeslice.
Parameters:
timeslice The timeslice to get the keys from.
Returns:
Returns a map with Key-Insertiontime pairs with all keys of that timeslice.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.frontend.Reaper.ReaperWorker.reap_timeslice(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.sliceLookup().
The documentation for this interface was generated from the following file:
server/src/main/java/de/zib/vold/volatilelogic/SlicedDirectory.java