VolD: de.zib.vold.common.Key Class Reference
de.zib.vold.common.Key Class Reference
A Key as a part of VolD entries.
Public Member Functions
Key (String scope, String type, String keyname) throws IllegalArgumentException
Construct a Key with all necessary informations.
String get_scope ()
Get the scope of the key.
String get_type ()
Get the type of the key.
String get_keyname ()
Get the name of the key.
String toString ()
Convert the key to readable and printable version.
List< String > _buildkey ()
Convert the key to the language used in volatilelogic.
boolean equals (Object obj)
Compare this key with another key.
int hashCode ()
Compute the hash code of this key.
Static Public Member Functions
static Key buildkey (List< String > key) throws IllegalArgumentException
Construct a key from list of strings.
Private Attributes
final String scope
final String type
final String keyname
Detailed Description
A Key as a part of VolD entries.
A Key is defined by a scope, a type and a keyname. The scope is any valid UNIX-style path. The type and keyname are arbitrary strings.
See also:
URIKey
Definition at line 19 of file Key.java.
Constructor & Destructor Documentation
de.zib.vold.common.Key.Key (String scope, String type, String keyname) throws IllegalArgumentException
Construct a Key with all necessary informations.
Parameters:
scope The scope of the key.
type The type of the key.
keyname The name of the key.
Definition at line 28 of file Key.java.
References de.zib.vold.common.Key.equals(), de.zib.vold.common.Key.keyname, de.zib.vold.common.Key.scope, and de.zib.vold.common.Key.type.
Referenced by de.zib.vold.common.Key.buildkey().
Member Function Documentation
List< String > de.zib.vold.common.Key._buildkey ()
Convert the key to the language used in volatilelogic.
Returns:
The converted key.
Definition at line 132 of file Key.java.
References de.zib.vold.common.Key.keyname, de.zib.vold.common.Key.scope, and de.zib.vold.common.Key.type.
Referenced by de.zib.vold.frontend.Frontend.insert(), de.zib.vold.frontend.Frontend.lookup(), de.zib.vold.frontend.Frontend.refresh(), de.zib.vold.frontend.Frontend.scopeLookup(), and de.zib.vold.common.Key.toString().
static Key de.zib.vold.common.Key.buildkey (List< String > key) throws IllegalArgumentException [static]
Construct a key from list of strings.
Parameters:
key The key in a format used in the volatilelogic package.
Returns:
The appropriate Key object.
Definition at line 116 of file Key.java.
References de.zib.vold.common.Key.Key().
Referenced by de.zib.vold.replication.RESTVoldReplicator.insert(), de.zib.vold.replication.RESTVoldReplicator.refresh(), and de.zib.vold.frontend.Frontend.scopeLookup().
boolean de.zib.vold.common.Key.equals (Object obj)
Compare this key with another key.
Returns:
true, iff this key represents the same key as obj.
Definition at line 148 of file Key.java.
References de.zib.vold.common.Key.get_keyname(), de.zib.vold.common.Key.get_scope(), and de.zib.vold.common.Key.get_type().
Referenced by de.zib.vold.common.Key.Key().
String de.zib.vold.common.Key.get_keyname ()
Get the name of the key.
Returns:
The name of the key.
Definition at line 95 of file Key.java.
References de.zib.vold.common.Key.keyname.
Referenced by de.zib.vold.client.RESTClient.delete(), de.zib.vold.common.Key.equals(), de.zib.vold.userInterface.RESTController.get(), de.zib.vold.common.Key.hashCode(), de.zib.vold.frontend.Frontend.lookup(), de.zib.vold.userInterface.ABI.main(), de.zib.vold.userInterface.RESTController.post(), de.zib.vold.client.RESTClient.refresh(), de.zib.vold.frontend.Frontend.scopeLookup(), and de.zib.vold.common.URIKey.toURIString().
String de.zib.vold.common.Key.get_scope ()
Get the scope of the key.
Returns:
The scope of the key.
Definition at line 75 of file Key.java.
References de.zib.vold.common.Key.scope.
Referenced by de.zib.vold.client.RESTClient.delete(), de.zib.vold.common.Key.equals(), de.zib.vold.userInterface.RESTController.get(), de.zib.vold.common.Key.hashCode(), de.zib.vold.frontend.Frontend.lookup(), de.zib.vold.userInterface.ABI.main(), de.zib.vold.userInterface.RESTController.post(), de.zib.vold.client.RESTClient.refresh(), de.zib.vold.frontend.Frontend.scopeLookup(), and de.zib.vold.common.URIKey.toURIString().
String de.zib.vold.common.Key.get_type ()
Get the type of the key.
Returns:
The type of the key.
Definition at line 85 of file Key.java.
References de.zib.vold.common.Key.type.
Referenced by de.zib.vold.client.RESTClient.delete(), de.zib.vold.common.Key.equals(), de.zib.vold.userInterface.RESTController.get(), de.zib.vold.common.Key.hashCode(), de.zib.vold.frontend.Frontend.lookup(), de.zib.vold.userInterface.ABI.main(), de.zib.vold.userInterface.RESTController.post(), de.zib.vold.client.RESTClient.refresh(), de.zib.vold.frontend.Frontend.scopeLookup(), and de.zib.vold.common.URIKey.toURIString().
int de.zib.vold.common.Key.hashCode ()
Compute the hash code of this key.
Returns:
The hash code of this key.
Definition at line 175 of file Key.java.
References de.zib.vold.common.Key.get_keyname(), de.zib.vold.common.Key.get_scope(), and de.zib.vold.common.Key.get_type().
String de.zib.vold.common.Key.toString ()
Convert the key to readable and printable version.
Returns:
A readable and printable version of the key.
Definition at line 105 of file Key.java.
References de.zib.vold.common.Key._buildkey().
Referenced by de.zib.vold.frontend.Frontend.lookup().
Member Data Documentation
final String de.zib.vold.common.Key.keyname [private]
Definition at line 184 of file Key.java.
Referenced by de.zib.vold.common.Key._buildkey(), de.zib.vold.common.Key.get_keyname(), and de.zib.vold.common.Key.Key().
final String de.zib.vold.common.Key.scope [private]
Definition at line 182 of file Key.java.
Referenced by de.zib.vold.common.Key._buildkey(), de.zib.vold.common.Key.get_scope(), and de.zib.vold.common.Key.Key().
final String de.zib.vold.common.Key.type [private]
Definition at line 183 of file Key.java.
Referenced by de.zib.vold.common.Key._buildkey(), de.zib.vold.common.Key.get_type(), and de.zib.vold.common.Key.Key().
The documentation for this class was generated from the following file:
common/src/main/java/de/zib/vold/common/Key.java