VolD: de.zib.vold.replication.RESTVoldReplicator Class Reference
de.zib.vold.replication.RESTVoldReplicator Class Reference
Replicator delegating all requests to another vold REST based service.
Public Member Functions
RESTVoldReplicator ()
Construct an unitialized RESTVoldReplicator.
void setBaseURL (String baseURL)
Set the REST base URL to delegate all write requests to.
void checkState ()
Internal method which acts as part of the guard of all public methods.
void insert (List< String > key, Set< String > value)
Delegate an insert request.
void refresh (List< String > key)
Delegate a refresh request.
void delete (List< String > key)
Delegate a delete request.
Protected Attributes
final Logger log = LoggerFactory.getLogger(this.getClass())
Package Attributes
RESTClient rest
Detailed Description
Replicator delegating all requests to another vold REST based service.
Note:
Since the vold frontend has another interface language (using the class Key for keys instead of lists of strings), the keys have to be build up. Hence, when using this replicator, the keys given here need the format specified for Key.buildkey.
See also:
Replicator
Key
RESTController
Definition at line 26 of file RESTVoldReplicator.java.
Constructor & Destructor Documentation
de.zib.vold.replication.RESTVoldReplicator.RESTVoldReplicator ()
Construct an unitialized RESTVoldReplicator.
Definition at line 35 of file RESTVoldReplicator.java.
References de.zib.vold.replication.RESTVoldReplicator.rest.
Member Function Documentation
void de.zib.vold.replication.RESTVoldReplicator.checkState ()
Internal method which acts as part of the guard of all public methods.
Definition at line 51 of file RESTVoldReplicator.java.
References de.zib.vold.client.RESTClient.checkState(), and de.zib.vold.replication.RESTVoldReplicator.rest.
Referenced by de.zib.vold.replication.RESTVoldReplicator.insert(), and de.zib.vold.replication.RESTVoldReplicator.refresh().
void de.zib.vold.replication.RESTVoldReplicator.delete (List< String > key)
Delegate a delete request.
Parameters:
key The key to replicate the request for.
Implements de.zib.vold.replication.Replicator.
Definition at line 131 of file RESTVoldReplicator.java.
void de.zib.vold.replication.RESTVoldReplicator.insert (List< String > key, Set< String > value)
Delegate an insert request.
Parameters:
key The key to replicate the request for.
value The values associated to the key.
Implements de.zib.vold.replication.Replicator.
Definition at line 70 of file RESTVoldReplicator.java.
References de.zib.vold.common.Key.buildkey(), de.zib.vold.replication.RESTVoldReplicator.checkState(), de.zib.vold.client.RESTClient.insert(), de.zib.vold.replication.RESTVoldReplicator.log, and de.zib.vold.replication.RESTVoldReplicator.rest.
void de.zib.vold.replication.RESTVoldReplicator.refresh (List< String > key)
Delegate a refresh request.
Parameters:
key The key to replicate request for.
Implements de.zib.vold.replication.Replicator.
Definition at line 99 of file RESTVoldReplicator.java.
References de.zib.vold.common.Key.buildkey(), de.zib.vold.replication.RESTVoldReplicator.checkState(), de.zib.vold.replication.RESTVoldReplicator.log, de.zib.vold.client.RESTClient.refresh(), and de.zib.vold.replication.RESTVoldReplicator.rest.
void de.zib.vold.replication.RESTVoldReplicator.setBaseURL (String baseURL)
Set the REST base URL to delegate all write requests to.
Definition at line 43 of file RESTVoldReplicator.java.
References de.zib.vold.replication.RESTVoldReplicator.rest, and de.zib.vold.client.RESTClient.setBaseURL().
Member Data Documentation
final Logger de.zib.vold.replication.RESTVoldReplicator.log = LoggerFactory.getLogger(this.getClass()) [protected]
Definition at line 28 of file RESTVoldReplicator.java.
Referenced by de.zib.vold.replication.RESTVoldReplicator.insert(), and de.zib.vold.replication.RESTVoldReplicator.refresh().
RESTClient de.zib.vold.replication.RESTVoldReplicator.rest [package]
Definition at line 30 of file RESTVoldReplicator.java.
Referenced by de.zib.vold.replication.RESTVoldReplicator.checkState(), de.zib.vold.replication.RESTVoldReplicator.insert(), de.zib.vold.replication.RESTVoldReplicator.refresh(), de.zib.vold.replication.RESTVoldReplicator.RESTVoldReplicator(), and de.zib.vold.replication.RESTVoldReplicator.setBaseURL().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/replication/RESTVoldReplicator.java