VolD: de.zib.vold.volatilelogic.ReplicatedVolatileDirectory Class Reference
de.zib.vold.volatilelogic.ReplicatedVolatileDirectory Class Reference
Proxy for VolatileDirectory replicating all write requests.
Classes
class DeleteThread
Helper class to delete an entry concurrently.
class InsertThread
Helper class to insert an entry concurrently.
class RefreshThread
Helper class to refresh an entry concurrently.
Public Member Functions
ReplicatedVolatileDirectory (VolatileDirectory backend, Replicator replicator)
Construct an initialized ReplicatedVolatileDirectory.
ReplicatedVolatileDirectory ()
Construct an uninitialized ReplicatedVolatileDirectory.
void setDirectory (VolatileDirectory directory)
Set the backend to delegate all requests to.
void setReplicator (Replicator replicator)
Set the replicator to replicate all write requests to.
void checkState ()
Internal method which acts as part of the guard of all public methods.
long getActualSlice ()
A delegator for TimeSlice.getActualSlice().
long getNumberOfSlices ()
A delegator for TimeSlice.getNumberOfSlices().
long getTimeSliceSize ()
A delegator for TimeSlice.getTimeSliceSize().
void insert (List< String > key, Set< String > value)
Insert a key with its set of values.
void refresh (List< String > key)
Refresh a key.
void delete (List< String > key)
Delete a key.
Set< String > lookup (List< String > key)
Delegate a lookup request to the backend.
Map< List< String >, Set
< String > > prefixLookup (List< String > key)
Delegate a prefixlookup to the backend.
Map< List< String >, DateTime > sliceLookup (long slice)
Delegate a slicelookup to the backend.
Protected Attributes
final Log log = LogFactory.getLog(this.getClass())
Private Attributes
VolatileDirectory backend
Replicator replicator
Detailed Description
Proxy for VolatileDirectory replicating all write requests.
Author:
Jörg Bachmann (bachmann@zib.de)
Definition at line 21 of file ReplicatedVolatileDirectory.java.
Constructor & Destructor Documentation
de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.ReplicatedVolatileDirectory (VolatileDirectory backend, Replicator replicator)
Construct an initialized ReplicatedVolatileDirectory.
Parameters:
backend The backend which this class is the proxy for.
replicator The replicator to replicate all write requests to.
Definition at line 34 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.replicator.
de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.ReplicatedVolatileDirectory ()
Construct an uninitialized ReplicatedVolatileDirectory.
Definition at line 43 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.replicator.
Member Function Documentation
void de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState ()
Internal method which acts as part of the guard of all public methods.
Definition at line 68 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.replicator.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.delete(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getActualSlice(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getNumberOfSlices(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getTimeSliceSize(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.insert(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.lookup(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.prefixLookup(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.refresh(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.sliceLookup().
void de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.delete (List< String > key)
Delete a key.
The request handled be done concurrently at the replicator and the backend.
Parameters:
key The key to delete.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 208 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), de.zib.vold.replication.Replicator.delete(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.log, and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.replicator.
long de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getActualSlice ()
A delegator for TimeSlice.getActualSlice().
See also:
TimeSlice
Implements de.zib.vold.volatilelogic.SlicedDirectory.
Definition at line 82 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), and de.zib.vold.volatilelogic.SlicedDirectory.getActualSlice().
long de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getNumberOfSlices ()
A delegator for TimeSlice.getNumberOfSlices().
See also:
TimeSlice
Implements de.zib.vold.volatilelogic.SlicedDirectory.
Definition at line 98 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), and de.zib.vold.volatilelogic.SlicedDirectory.getNumberOfSlices().
long de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getTimeSliceSize ()
A delegator for TimeSlice.getTimeSliceSize().
See also:
TimeSlice
Implements de.zib.vold.volatilelogic.SlicedDirectory.
Definition at line 114 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), and de.zib.vold.volatilelogic.SlicedDirectory.getTimeSliceSize().
void de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.insert (List< String > key, Set< String > value)
Insert a key with its set of values.
The insertion will be done concurrently at the replicator and the backend.
Parameters:
key The key to insert.
value The values associated to the key.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 134 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), de.zib.vold.replication.Replicator.insert(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.log, and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.replicator.
Set< String > de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.lookup (List< String > key)
Delegate a lookup request to the backend.
Parameters:
key The key to query.
Returns:
The values for that key or null if the key has not been found.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 332 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), and de.zib.vold.volatilelogic.SimpleDirectory.lookup().
Map< List< String >, Set< String > > de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.prefixLookup (List< String > key)
Delegate a prefixlookup to the backend.
Parameters:
key The prefix of the keys to be found.
Returns:
The map containing all keys beginning with the prefix and all its associated values.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 349 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), and de.zib.vold.volatilelogic.SimpleDirectory.prefixLookup().
void de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.refresh (List< String > key)
Refresh a key.
The request will be handled concurrently at the replicator and the backend.
Parameters:
key The key to refresh.
Implements de.zib.vold.volatilelogic.SimpleDirectory.
Definition at line 171 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.log, de.zib.vold.replication.Replicator.refresh(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.replicator.
void de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.setDirectory (VolatileDirectory directory)
Set the backend to delegate all requests to.
Definition at line 52 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend.
void de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.setReplicator (Replicator replicator)
Set the replicator to replicate all write requests to.
Definition at line 60 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.replicator.
Map< List< String >, DateTime > de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.sliceLookup (long slice)
Delegate a slicelookup to the backend.
Parameters:
slice The slice to get all keys from.
Returns:
The keys in that slice and its timestamps.
Implements de.zib.vold.volatilelogic.SlicedDirectory.
Definition at line 366 of file ReplicatedVolatileDirectory.java.
References de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend, de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), and de.zib.vold.volatilelogic.SlicedDirectory.sliceLookup().
Member Data Documentation
VolatileDirectory de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.backend [private]
Definition at line 25 of file ReplicatedVolatileDirectory.java.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.delete(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getActualSlice(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getNumberOfSlices(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.getTimeSliceSize(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.insert(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.lookup(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.prefixLookup(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.refresh(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.ReplicatedVolatileDirectory(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.setDirectory(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.sliceLookup().
final Log de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.log = LogFactory.getLog(this.getClass()) [protected]
Definition at line 23 of file ReplicatedVolatileDirectory.java.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.delete(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.insert(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.refresh().
Replicator de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.replicator [private]
Definition at line 26 of file ReplicatedVolatileDirectory.java.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.checkState(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.delete(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.insert(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.refresh(), de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.ReplicatedVolatileDirectory(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.setReplicator().
The documentation for this class was generated from the following file:
server/src/main/java/de/zib/vold/volatilelogic/ReplicatedVolatileDirectory.java