VolD: de.zib.vold.common.URIKey Class Reference
de.zib.vold.common.URIKey Class Reference
A normalized Key used in REST language.
Public Member Functions
URIKey (String source, String scope, String type, String keyname, boolean refresh, boolean delete, String enc)
Construct a URIKey with all necessary informations.
String getSource ()
Get the source of the key.
Key getKey ()
Reduce the key to a Key.
boolean isRefresh ()
Flag whether this URIKey is a refresh request.
boolean isDelete ()
Flag whether this URIKey is a delete request.
String toURIString ()
Get the normalized key.
Static Public Member Functions
static URIKey fromURIString (String uri, String enc)
Build a URIKey from a normalized URIKey.
Private Attributes
final String source
final Key key
final boolean refresh
final boolean delete
final String enc
Detailed Description
A normalized Key used in REST language.
See also:
Key
Definition at line 13 of file URIKey.java.
Constructor & Destructor Documentation
de.zib.vold.common.URIKey.URIKey (String source, String scope, String type, String keyname, boolean refresh, boolean delete, String enc)
Construct a URIKey with all necessary informations.
Parameters:
source The source where the key comes from.
scope The scope of the key.
type The type of the key.
keyname The name of the key.
refresh Whether this is a refresh request.
delete Whether this is a delete request.
enc The encoding used to encode the key to a string.
Definition at line 33 of file URIKey.java.
References de.zib.vold.common.URIKey.enc, de.zib.vold.common.URIKey.key, de.zib.vold.common.URIKey.refresh, and de.zib.vold.common.URIKey.source.
Referenced by de.zib.vold.common.URIKey.fromURIString().
Member Function Documentation
static URIKey de.zib.vold.common.URIKey.fromURIString (String uri, String enc) [static]
Build a URIKey from a normalized URIKey.
Parameters:
uri The normalized key to decode.
enc The encoding which had been used to encode/normalize the string.
Returns:
The URIKey.
Definition at line 133 of file URIKey.java.
References de.zib.vold.common.URIKey.refresh, de.zib.vold.common.URIKey.source, and de.zib.vold.common.URIKey.URIKey().
Referenced by de.zib.vold.userInterface.RESTController.get(), and de.zib.vold.userInterface.RESTController.post().
Key de.zib.vold.common.URIKey.getKey ()
Reduce the key to a Key.
Returns:
The Key object.
See also:
Key
Definition at line 65 of file URIKey.java.
References de.zib.vold.common.URIKey.key.
Referenced by de.zib.vold.userInterface.RESTController.get(), and de.zib.vold.userInterface.RESTController.post().
String de.zib.vold.common.URIKey.getSource ()
Get the source of the key.
Returns:
The source of the key.
Definition at line 53 of file URIKey.java.
References de.zib.vold.common.URIKey.source.
Referenced by de.zib.vold.userInterface.RESTController.post().
boolean de.zib.vold.common.URIKey.isDelete ()
Flag whether this URIKey is a delete request.
Definition at line 81 of file URIKey.java.
Referenced by de.zib.vold.userInterface.RESTController.post().
boolean de.zib.vold.common.URIKey.isRefresh ()
Flag whether this URIKey is a refresh request.
Definition at line 73 of file URIKey.java.
References de.zib.vold.common.URIKey.refresh.
Referenced by de.zib.vold.userInterface.RESTController.post().
String de.zib.vold.common.URIKey.toURIString ()
Get the normalized key.
Returns:
a unique string identifying this URIKey.
Definition at line 91 of file URIKey.java.
References de.zib.vold.common.URIKey.enc, de.zib.vold.common.Key.get_keyname(), de.zib.vold.common.Key.get_scope(), de.zib.vold.common.Key.get_type(), de.zib.vold.common.URIKey.key, de.zib.vold.common.URIKey.refresh, and de.zib.vold.common.URIKey.source.
Referenced by de.zib.vold.client.RESTClient.delete(), de.zib.vold.client.RESTClient.insert(), and de.zib.vold.client.RESTClient.refresh().
Member Data Documentation
final boolean de.zib.vold.common.URIKey.delete [private]
Definition at line 19 of file URIKey.java.
final String de.zib.vold.common.URIKey.enc [private]
Definition at line 20 of file URIKey.java.
Referenced by de.zib.vold.common.URIKey.toURIString(), and de.zib.vold.common.URIKey.URIKey().
final Key de.zib.vold.common.URIKey.key [private]
Definition at line 16 of file URIKey.java.
Referenced by de.zib.vold.common.URIKey.getKey(), de.zib.vold.common.URIKey.toURIString(), and de.zib.vold.common.URIKey.URIKey().
final boolean de.zib.vold.common.URIKey.refresh [private]
Definition at line 18 of file URIKey.java.
Referenced by de.zib.vold.common.URIKey.fromURIString(), de.zib.vold.common.URIKey.isRefresh(), de.zib.vold.common.URIKey.toURIString(), and de.zib.vold.common.URIKey.URIKey().
final String de.zib.vold.common.URIKey.source [private]
Definition at line 15 of file URIKey.java.
Referenced by de.zib.vold.common.URIKey.fromURIString(), de.zib.vold.common.URIKey.getSource(), de.zib.vold.common.URIKey.toURIString(), and de.zib.vold.common.URIKey.URIKey().
The documentation for this class was generated from the following file:
common/src/main/java/de/zib/vold/common/URIKey.java