VolD: de.zib.vold.volatilelogic.SimpleDirectory Interface Reference
de.zib.vold.volatilelogic.SimpleDirectory Interface Reference
Interface for volatile directory usage.
Public Member Functions
void refresh (List< String > key)
Refresh a key.
void delete (List< String > key)
Delete a key.
Set< String > lookup (List< String > key)
Query a key.
Map< List< String >, Set
< String > > prefixLookup (List< String > prefix)
Query all keys beginning with a certain prefix.
Package Functions
void insert (List< String > key, Set< String > value)
Insert a key with its values.
Detailed Description
Interface for volatile directory usage.
Each volatile directory must implement this interface. It provides the methods used for read and write access by the Frontend.
This interface is just one part of the main interface VolatileDirectory exported by this package.
Note:
The backend uses lists of strings for storing values. Since there are some backends having a set semantic nonetheless, the set semantic is enforced here.
See also:
Frontend
Definition at line 23 of file SimpleDirectory.java.
Member Function Documentation
void de.zib.vold.volatilelogic.SimpleDirectory.delete (List< String > key)
Delete a key.
Parameters:
key The key to delete.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
void de.zib.vold.volatilelogic.SimpleDirectory.insert (List< String > key, Set< String > value) [package]
Insert a key with its values.
Parameters:
key The key to insert.
value The set of values associated with the keys.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.replication.LocalReplicator.insert(), de.zib.vold.frontend.Frontend.insert(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.InsertThread.run().
Set< String > de.zib.vold.volatilelogic.SimpleDirectory.lookup (List< String > key)
Query a key.
Parameters:
key The key to query.
Returns:
null if that key does not exist or its set of values otherwise.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.lookup().
Map< List< String >, Set< String > > de.zib.vold.volatilelogic.SimpleDirectory.prefixLookup (List< String > prefix)
Query all keys beginning with a certain prefix.
Parameters:
prefix The prefix all queried keys should have.
Returns:
A map with all found keys and its associated values.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.prefixLookup(), and de.zib.vold.frontend.Frontend.scopeLookup().
void de.zib.vold.volatilelogic.SimpleDirectory.refresh (List< String > key)
Refresh a key.
Refreshing a key means to update the timestamp of the key.
Parameters:
key The key to refresh.
Implemented in de.zib.vold.volatilelogic.ReplicatedVolatileDirectory, and de.zib.vold.volatilelogic.VolatileDirectoryImpl.
Referenced by de.zib.vold.replication.LocalReplicator.refresh(), de.zib.vold.frontend.Frontend.refresh(), and de.zib.vold.volatilelogic.ReplicatedVolatileDirectory.RefreshThread.run().
The documentation for this interface was generated from the following file:
server/src/main/java/de/zib/vold/volatilelogic/SimpleDirectory.java